version: '3.8'

services:
  web:
    build: .
    ports:
      - "4174:4174"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://wph-backend.gregdoesdev.xyz
    restart: unless-stopped